addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.17")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"          % "0.8.1")
addSbtPlugin("com.47deg"                 % "sbt-microsites"           % "1.3.4")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"              % "0.6.3")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                  % "0.4.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.5.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.2")
